/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2026. All rights reserved.
 *
 * AlltoAllAttnUpdateAllGather ACLNN Two-Stage Interface Implementation
 *
 * Pattern: MC2 fused operator ACLNN, mirrors aclnn_mask_all_to_all_v2.cpp.
 *
 * Inplace: outer API takes 3 tensors (attn / lse / mask_num); after OpDef
 * rename to *_ref (Input/Output 同名 + _ref 后缀), opbuild emits
 * NnopbaseSetRef so inner API drops the duplicate Output params — pass each
 * tensor ONCE. Kernel entry receives 5 GM_ADDR with attn==attn_out and
 * lse==lse_out guaranteed by SetRef. Mirrors mask_all_to_all_v2 inner API.
 *
 * Other rules:
 * - Must call NnopbaseSetHcclServerType(executor, MTE) before inner-execute
 *   to route HCCL through MTE server. peermem-only MC2 算子范式
 *   (与 attention_to_ffn / ffn_to_attention / distribute_barrier 一致):
 *   kernel 不调任何 hccl_.AllToAll/AllGather/AllReduce collective, 仅通过
 *   winContext_->localWindowsIn + remoteRes[i] 自管 SDMA 搬运, 所以 AICPU
 *   server 状态机不参与, 选 MTE.
 * - Inner API (aclnnInner*) is auto-generated by build system from OpDef.
 * - DFX id = 0x60003 (occupied: 0x60000 matmul_*, 0x60001 mask_attn_update_allgather,
 *   0x60002 mask_all_to_all_v2).
 */

#include "aclnn_allto_all_attn_update_all_gather.h"
#include "securec.h"
#include "acl/acl.h"
#include "aclnn_kernels/common/op_error_check.h"
#include "opdev/common_types.h"
#include "opdev/make_op_executor.h"
#include "opdev/op_dfx.h"
#include "opdev/op_executor.h"
#include "opdev/op_log.h"
#include "opdev/platform.h"

using namespace op;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t id;
    const char *funcName;
    bool hasReg;
} NnopbaseDfxId;

// 9.0.0+ : NnopbaseSetHcclServerType 第二参数从 int 改成强类型 enum.
// 我们走 MTE server (= 1, 8.5.1 用的值实质也是 MTE).
enum NnopbaseHcclServerType {
    NNOPBASE_HCCL_SERVER_TYPE_AICPU = 0,
    NNOPBASE_HCCL_SERVER_TYPE_MTE,
    NNOPBASE_HCCL_SERVER_TYPE_CCU,
    NNOPBASE_HCCL_SERVER_TYPE_END
};

// Inner implementation auto-generated from OpDef. OpDef uses Input("attn_ref")
// + Output("attn_ref") same name + _ref suffix → opbuild emits NnopbaseSetRef
// → inner API drops the Output params (mirrors mask_all_to_all_v2 inner sig).
extern aclnnStatus aclnnInnerAlltoAllAttnUpdateAllGatherGetWorkspaceSize(
    const aclTensor *attn_ref, const aclTensor *lse_ref, const aclTensor *mask_num,
    char *group, int64_t group_size,
    uint64_t *workspaceSize, aclOpExecutor **executor);

extern aclnnStatus aclnnInnerAlltoAllAttnUpdateAllGather(
    void *workspace, uint64_t workspaceSize,
    aclOpExecutor *executor, aclrtStream stream);

// MC2 / nnopbase utilities (weak: NnopbaseSetHcclServerType may be unresolved
// in older nnopbase builds — caller must null-check).
extern "C" uint64_t NnopbaseMsprofSysTime();
extern "C" void NnopbaseReportApiInfo(const uint64_t beginTime, NnopbaseDfxId &dfxId);
extern "C" void __attribute__((weak)) NnopbaseSetHcclServerType(void *executor, NnopbaseHcclServerType sType);

// ===== Parameter Validation =====

static bool CheckNotNull(const aclTensor *attn, const aclTensor *lse,
                         const aclTensor *mask_num)
{
    OP_CHECK_NULL(attn,     return false);
    OP_CHECK_NULL(lse,      return false);
    OP_CHECK_NULL(mask_num, return false);
    return true;
}

static const std::initializer_list<op::DataType> ATTN_DTYPE_LIST = {
    op::DataType::DT_BF16
};
static const std::initializer_list<op::DataType> LSE_DTYPE_LIST = {
    op::DataType::DT_FLOAT
};
static const std::initializer_list<op::DataType> MASK_DTYPE_LIST = {
    op::DataType::DT_INT32
};

static bool CheckDtypeValid(const aclTensor *attn, const aclTensor *lse,
                            const aclTensor *mask_num)
{
    OP_CHECK_DTYPE_NOT_SUPPORT(attn,     ATTN_DTYPE_LIST, return false);
    OP_CHECK_DTYPE_NOT_SUPPORT(lse,      LSE_DTYPE_LIST,  return false);
    OP_CHECK_DTYPE_NOT_SUPPORT(mask_num, MASK_DTYPE_LIST, return false);
    return true;
}

static bool CheckShape(const aclTensor *attn, const aclTensor *lse,
                       const aclTensor *mask_num)
{
    // 2D layout: attn [T·cp, n/cp·D], lse [T·cp, n/cp]
    OP_CHECK_WRONG_DIMENSION(attn, 2, return false);
    OP_CHECK_WRONG_DIMENSION(lse,  2, return false);

    // mask_num: 0-d scalar tensor (aclgraph capture requirement)
    int64_t maskDimNum = static_cast<int64_t>(mask_num->GetViewShape().GetDimNum());
    if (maskDimNum != 0) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID,
            "mask_num must be 0-d (scalar) tensor for aclgraph; got %ld dims", maskDimNum);
        return false;
    }

    int64_t totalT    = attn->GetViewShape().GetDim(0);
    int64_t hDim      = attn->GetViewShape().GetDim(1);
    int64_t lseTotalT = lse->GetViewShape().GetDim(0);
    int64_t lseDim    = lse->GetViewShape().GetDim(1);

    if (lseTotalT != totalT) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID,
            "lse.dim(0)=%ld must equal attn.dim(0)=%ld (both = T·cp)", lseTotalT, totalT);
        return false;
    }
    if (lseDim == 0 || (hDim % lseDim) != 0) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID,
            "attn.dim(1)=%ld must be a positive multiple of lse.dim(1)=%ld (= n/cp · D / n/cp = D)",
            hDim, lseDim);
        return false;
    }
    return true;
}

static aclnnStatus CheckParams(const aclTensor *attn, const aclTensor *lse,
                               const aclTensor *mask_num,
                               int64_t group_size)
{
    if (!CheckNotNull(attn, lse, mask_num))    return ACLNN_ERR_PARAM_NULLPTR;
    if (!CheckDtypeValid(attn, lse, mask_num)) return ACLNN_ERR_PARAM_INVALID;
    if (!CheckShape(attn, lse, mask_num))      return ACLNN_ERR_PARAM_INVALID;

    // CP sizes: 1, 2, 4, 8, 16  (cp_max = 16, kernel buff_[16] hard limit)
    if (group_size != 1 && group_size != 2 && group_size != 4 &&
        group_size != 8 && group_size != 16) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID,
            "group_size must be one of {1,2,4,8,16}, got %ld", group_size);
        return ACLNN_ERR_PARAM_INVALID;
    }

    // totalT must be divisible by group_size (both Phase A pack and Phase C
    // unpack walk in cp-strided rows — non-divisible totalT misaligns boundary).
    int64_t totalT = attn->GetViewShape().GetDim(0);
    if (totalT % group_size != 0) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID,
            "totalT=%ld must be a multiple of group_size=%ld", totalT, group_size);
        return ACLNN_ERR_PARAM_INVALID;
    }
    return ACLNN_SUCCESS;
}

// ============================================================================
// Stage 1: GetWorkspaceSize  (inplace: outer API takes 3 tensors)
// ============================================================================

aclnnStatus aclnnAlltoAllAttnUpdateAllGatherGetWorkspaceSize(
    const aclTensor *attn,
    const aclTensor *lse,
    const aclTensor *mask_num,
    char *group,
    int64_t group_size,
    uint64_t *workspaceSize,
    aclOpExecutor **executor)
{
    uint64_t timeStamp = NnopbaseMsprofSysTime();

    auto retParam = CheckParams(attn, lse, mask_num, group_size);
    CHECK_RET(retParam == ACLNN_SUCCESS, retParam);

    // Empty tensor short-circuit: totalT == 0 means nothing to compute
    if (attn->IsEmpty()) {
        auto uniqueExecutor = CREATE_EXECUTOR();
        CHECK_RET(uniqueExecutor.get() != nullptr, ACLNN_ERR_INNER_CREATE_EXECUTOR);
        *workspaceSize = 0;
        uniqueExecutor.ReleaseTo(executor);
        return ACLNN_SUCCESS;
    }

    OP_LOGD("AlltoAllAttnUpdateAllGather inplace, attn %s, lse %s, group_size=%ld",
            attn->ToString().GetString(), lse->ToString().GetString(), group_size);

    // Inplace via OpDef SetRef: pass attn / lse ONCE. Framework binds
    // Output("attn_ref") slot to Input("attn_ref") same address (likewise lse).
    aclnnStatus ret = aclnnInnerAlltoAllAttnUpdateAllGatherGetWorkspaceSize(
        attn, lse, mask_num, group, group_size,
        workspaceSize, executor);
    OP_LOGD("AlltoAllAttnUpdateAllGather, aclnnInnerGetWorkspaceSize ret = %d.", ret);

    static NnopbaseDfxId dfxId = {0x60003, __func__, false};
    NnopbaseReportApiInfo(timeStamp, dfxId);
    return ret;
}

// ============================================================================
// Stage 2: Execute
// ============================================================================

aclnnStatus aclnnAlltoAllAttnUpdateAllGather(
    void *workspace,
    uint64_t workspaceSize,
    aclOpExecutor *executor,
    aclrtStream stream)
{
    if (workspace == nullptr || workspaceSize == 0UL) {
        OP_LOGD("Skip api for empty tensor, workspace size %lu.", workspaceSize);
        return ACLNN_SUCCESS;
    }
    uint64_t timeStamp = NnopbaseMsprofSysTime();

    // MC2 operator: peermem-only (kernel 不调 hccl_.AllToAll/AllGather/AllReduce,
    // 仅通过 winContext_->localWindowsIn / remoteRes[i] 自管 SDMA 搬运).
    // 与 attention_to_ffn / ffn_to_attention / distribute_barrier 同范式: 用 MTE.
    // 8.5.1 我们写 `1` 实质就是 MTE (旧注释误标 AICPU, 已勘误).
    // weak symbol — null-check before call.
    if (NnopbaseSetHcclServerType) {
        NnopbaseSetHcclServerType(executor, NNOPBASE_HCCL_SERVER_TYPE_MTE);
    }

    auto ret = aclnnInnerAlltoAllAttnUpdateAllGather(workspace, workspaceSize, executor, stream);
    if (ret != 0) {
        OP_LOGE(ACLNN_ERR_INNER, "AlltoAllAttnUpdateAllGather launch aicore failed");
        return ACLNN_ERR_INNER;
    }

    static NnopbaseDfxId dfxId = {0x60003, __func__, false};
    NnopbaseReportApiInfo(timeStamp, dfxId);
    return ACLNN_SUCCESS;
}

#ifdef __cplusplus
}
#endif
